# Site settings
title: Logh
email: contato@logh.com.br
url: http://logh.com.br
description: "Tecnologia"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#303F9F'
  links: '#219ab3'

# Footer settings
footer: Logh

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/loghtecnologia
  - title: facebook
    url: https://facebook.com.br/loghtecnologia
  - title: github
    url: https://github.com/loghtecnologia
  - title: linkedin
    url: #
  - title: google-plus
    url: #
    

# Build settings
markdown: kramdown
permalink: pretty
